### ISSUE TITLE
ImportError: cannot import name 'six' from 'django.utils' on Django 3.0

### ISSUE THREAD

**Issue by bastbnl** [grantmcconnaughey/django-avatar#182]
I updated to Django 3.0 this morning and noticed this error:
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/brownpapersession/dev/brownpapersession/app/models.py", line 58, in <module>
    from avatar.models import Avatar
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/avatar/models.py", line 14, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/django/utils/__init__.py)
```

PR coming up

**Comment by grantmcconnaughey** [comment]
Fixed in #183
